server:
  port: 8761

spring:
  application:
    name: REGISTRY-SERVICE
  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:8761
        url:
          - http://localhost:9090  
eureka:
  client:
    register-with-eureka: false 
    fetch-registry: false   

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>   