server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:9191
        url:
          - http://localhost:9090
  cloud:
    config:
      uri:
        - http://localhost:9295
      name: CONFIG-SERVER  
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackuri: forward:/departmentServiceFallBack    
 
    
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>    
    