server:
  port: 9002
        
spring:
  application:
    name: USER-SERVICE
  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:9002
        url:
          - http://localhost:9090
  cloud:
    config:
      uri:
        - http://localhost:9295
      name: CONFIG-SERVER  
  zipkin:
    base-url: http://localhost:9411/     

    
management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>    